/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe for the platform (Cloud Run / uptime checks).
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Seasons */
        get: operations["get_seasons_api_seasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{year}/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Load Season */
        post: operations["load_season_api_seasons__year__load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seasons/{year}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Season Progress */
        get: operations["season_progress_api_seasons__year__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schedule */
        get: operations["get_schedule_api_schedule_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Games */
        get: operations["get_games_api_games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game */
        get: operations["get_game_api_games__game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game Ratings */
        get: operations["get_game_ratings_api_games__game_id__ratings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/lineup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game Lineup */
        get: operations["get_game_lineup_api_games__game_id__lineup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/players/{player_id}/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game Player Chart */
        get: operations["get_game_player_chart_api_games__game_id__players__player_id__chart_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player */
        get: operations["get_player_api_players__player_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_id}/comparables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player Comparables */
        get: operations["get_player_comparables_api_players__player_id__comparables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_id}/splits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player Splits */
        get: operations["get_player_splits_api_players__player_id__splits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{player_id}/def-splits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Player Def Splits
         * @description A defender's event line conditioned on one situational dimension.
         */
        get: operations["get_player_def_splits_api_players__player_id__def_splits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Team */
        get: operations["get_team_api_teams__team__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team}/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Team Roster */
        get: operations["get_team_roster_api_teams__team__roster_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team}/depth-chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Team Depth Chart
         * @description The team's current depth chart. The vendor feed is a daily snapshot
         *     with no per-week history (see DEPTH_CHART_SEL), so `week` is accepted
         *     for API compatibility but ignored, and a request for a season other
         *     than the snapshot's returns [] rather than passing off today's chart
         *     as historical.
         */
        get: operations["get_team_depth_chart_api_teams__team__depth_chart_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team}/splits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Team Splits
         * @description Team offense/defense rate profile conditioned on each situational
         *     dimension. Reads the materialized table; self-heals on a cold table.
         */
        get: operations["get_team_splits_api_teams__team__splits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{team}/injuries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Team Injuries
         * @description Most recent injury report for the team. If `week` is omitted, returns
         *     the latest week we have data for in the given season.
         */
        get: operations["get_team_injuries_api_teams__team__injuries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/team-analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Team Analytics
         * @description Read precomputed team analytics from the materialized table.
         *
         *     The heavy aggregation (150-line CTE over plays + schedules) used to run
         *     on every request. It now runs once during ingest and writes to the
         *     `team_season_analytics` table; this endpoint is a simple keyed SELECT.
         *
         *     If the row is missing (fresh DB, never-ingested season), the builder
         *     lazily materializes on first hit so the system self-heals.
         */
        get: operations["get_team_analytics_api_team_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Leaders */
        get: operations["get_leaders_api_leaders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wpa-leaders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Wpa Leaders */
        get: operations["get_wpa_leaders_api_wpa_leaders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/standings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Standings */
        get: operations["get_standings_api_standings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/power-rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Power Rankings */
        get: operations["get_power_rankings_api_power_rankings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask
         * @description Non-streaming answer (used by the eval and as a simple fallback).
         */
        post: operations["ask_api_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ask/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Stream
         * @description Server-Sent Events: streams the tool-call chain and the answer tokens as
         *     the agent works. Validation + rate limit run before the stream opens; errors
         *     that surface mid-stream (auth, upstream) arrive as an `error` event, since
         *     the HTTP status is already committed once streaming starts.
         */
        post: operations["ask_stream_api_ask_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gaps
         * @description Review the data gaps the assistant has logged — questions it couldn't
         *     fully answer because the platform is missing that stat/split/season.
         */
        get: operations["gaps_api_gaps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/scoreboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scoreboard */
        get: operations["get_scoreboard_api_live_scoreboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AskHistoryMessage */
        AskHistoryMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
            /** History */
            history?: components["schemas"]["AskHistoryMessage"][];
        };
        /** AskResponse */
        AskResponse: {
            /** Answer */
            answer: string;
            /** Data */
            data: {
                [key: string]: unknown;
            }[];
            /** Tools Used */
            tools_used: components["schemas"]["ToolCall"][];
        };
        /**
         * CombineData
         * @description One row per combine participant. Heights are recorded as '6-2' strings
         *     by the source; we leave them as strings for display rather than coercing.
         */
        CombineData: {
            /** Draft Year */
            draft_year: number | null;
            /** Draft Round */
            draft_round: number | null;
            /** Draft Ovr */
            draft_ovr: number | null;
            /** School */
            school: string | null;
            /** Pos */
            pos: string | null;
            /** Ht */
            ht: string | null;
            /** Wt */
            wt: number | null;
            /** Forty */
            forty: number | null;
            /** Bench */
            bench: number | null;
            /** Vertical */
            vertical: number | null;
            /** Broad Jump */
            broad_jump: number | null;
            /** Cone */
            cone: number | null;
            /** Shuttle */
            shuttle: number | null;
        };
        /**
         * DefensiveSplit
         * @description A defender's event line (tackles/sacks/TFL/QB hits/INT/PBU/FF)
         *     conditioned on one situational dimension. Counts only — nflfastR has no
         *     coverage data. Scrimmage plays only (special-teams tackles have no down).
         *     Served by /players/{id}/def-splits.
         */
        DefensiveSplit: {
            /** Season */
            season: number;
            /** Split Dim */
            split_dim: string;
            /** Split Value */
            split_value: string;
            /** Sort Order */
            sort_order: number | null;
            /** Tackles */
            tackles: number | null;
            /** Solo */
            solo: number | null;
            /** Assists */
            assists: number | null;
            /** Tfl */
            tfl: number | null;
            /** Sacks */
            sacks: number | null;
            /** Qb Hits */
            qb_hits: number | null;
            /** Interceptions */
            interceptions: number | null;
            /** Pass Breakups */
            pass_breakups: number | null;
            /** Forced Fumbles */
            forced_fumbles: number | null;
        };
        /**
         * DepthChartEntry
         * @description A depth-chart slot. depth_team is "1"/"2"/"3", where "1" is the
         *     starter at that depth_position. The vendor feed is a daily snapshot:
         *     season is derived from the snapshot date and week is always null.
         */
        DepthChartEntry: {
            /** Season */
            season: number;
            /** Week */
            week: number | null;
            /** Team */
            team: string;
            /** Formation */
            formation: string | null;
            /** Depth Position */
            depth_position: string | null;
            /** Depth Team */
            depth_team: string | null;
            /** Gsis Id */
            gsis_id: string | null;
            /** Full Name */
            full_name: string | null;
            /** Position */
            position: string | null;
            /** Jersey Number */
            jersey_number: string | null;
        };
        /** DivisionStandings */
        DivisionStandings: {
            /** Division */
            division: string;
            /** Teams */
            teams: components["schemas"]["StandingsRow"][];
        };
        /**
         * DraftInfo
         * @description One row per drafted player from `draft_picks`. Career achievement
         *     fields (`probowls`, `allpro`, `car_av`) come pre-aggregated from PFR.
         */
        DraftInfo: {
            /** Season */
            season: number;
            /** Round */
            round: number;
            /** Pick */
            pick: number;
            /** Team */
            team: string;
            /** College */
            college: string | null;
            /** Age */
            age: number | null;
            /** Probowls */
            probowls: number | null;
            /** Allpro */
            allpro: number | null;
            /** Car Av */
            car_av: number | null;
            /** Games */
            games: number | null;
        };
        /**
         * Game
         * @description A scheduled game; scores are null for unplayed games.
         */
        Game: {
            /** Game Id */
            game_id: string;
            /** Season */
            season: number;
            /** Game Type */
            game_type: string;
            /** Week */
            week: number;
            /** Gameday */
            gameday: string | null;
            /** Gametime */
            gametime: string | null;
            /** Away Team */
            away_team: string;
            /** Home Team */
            home_team: string;
            /** Away Score */
            away_score: number | null;
            /** Home Score */
            home_score: number | null;
            /** Away Qb Name */
            away_qb_name: string | null;
            /** Home Qb Name */
            home_qb_name: string | null;
            /** Spread Line */
            spread_line: number | null;
            /** Total Line */
            total_line: number | null;
            /** Roof */
            roof: string | null;
            /** Surface */
            surface: string | null;
            /** Temp */
            temp: number | null;
            /** Wind */
            wind: number | null;
            /** Stadium */
            stadium: string | null;
            /** Overtime */
            overtime: number | null;
            /** Div Game */
            div_game: number | null;
            /** Away Coach */
            away_coach?: string | null;
            /** Home Coach */
            home_coach?: string | null;
            /** Away Record */
            away_record?: string | null;
            /** Home Record */
            home_record?: string | null;
        };
        /**
         * GameDetail
         * @description Game detail returned by /games/{id}: game header + rosters + scoring + WP.
         */
        GameDetail: {
            /** Game Id */
            game_id: string;
            /** Season */
            season: number;
            /** Game Type */
            game_type: string;
            /** Week */
            week: number;
            /** Gameday */
            gameday: string | null;
            /** Gametime */
            gametime: string | null;
            /** Away Team */
            away_team: string;
            /** Home Team */
            home_team: string;
            /** Away Score */
            away_score: number | null;
            /** Home Score */
            home_score: number | null;
            /** Away Qb Name */
            away_qb_name: string | null;
            /** Home Qb Name */
            home_qb_name: string | null;
            /** Spread Line */
            spread_line: number | null;
            /** Total Line */
            total_line: number | null;
            /** Roof */
            roof: string | null;
            /** Surface */
            surface: string | null;
            /** Temp */
            temp: number | null;
            /** Wind */
            wind: number | null;
            /** Stadium */
            stadium: string | null;
            /** Overtime */
            overtime: number | null;
            /** Div Game */
            div_game: number | null;
            /** Away Coach */
            away_coach?: string | null;
            /** Home Coach */
            home_coach?: string | null;
            /** Away Record */
            away_record?: string | null;
            /** Home Record */
            home_record?: string | null;
            /** Away */
            away: components["schemas"]["GamePlayerStats"][];
            /** Home */
            home: components["schemas"]["GamePlayerStats"][];
            /** Quarter Scores */
            quarter_scores: components["schemas"]["QuarterScore"][];
            /** Win Prob */
            win_prob: components["schemas"]["WinProbPlay"][];
            /** Team Stats */
            team_stats: components["schemas"]["TeamGameStats"][];
            /** Scoring */
            scoring: components["schemas"]["ScoringPlay"][];
        };
        /** GameLineup */
        GameLineup: {
            /** Game Id */
            game_id: string;
            /** Season */
            season: number;
            /** Week */
            week: number;
            /** Away Team */
            away_team: string;
            /** Home Team */
            home_team: string;
            /** Away Coach */
            away_coach?: string | null;
            /** Home Coach */
            home_coach?: string | null;
            /** Join Match Rate */
            join_match_rate: number | null;
            /** Scoring */
            scoring: components["schemas"]["LineupScoringEvent"][];
            /** Teams */
            teams: components["schemas"]["LineupTeam"][];
        };
        /** GamePlayerRating */
        GamePlayerRating: {
            /** Player Id */
            player_id: string;
            /** Player Name */
            player_name: string | null;
            /** Team */
            team: string | null;
            /** Position */
            position: string | null;
            /** Position Group */
            position_group: string;
            /** Rating */
            rating: number | null;
            /** Raw Score */
            raw_score: number | null;
            /** Plays Counted */
            plays_counted: number | null;
            /** Epa Total */
            epa_total: number | null;
            /** Turnovers */
            turnovers: number | null;
            /** Def Events Score */
            def_events_score: number | null;
            /** Fg Points */
            fg_points: number | null;
        };
        /**
         * GamePlayerStats
         * @description Per-game player line returned in /games/{id} under away[] / home[].
         *
         *     Stat columns come back as DOUBLE from DuckDB (DEFAULT 0), so they are
         *     floats even when conceptually counts (touchdowns, attempts, etc.).
         */
        GamePlayerStats: {
            /** Player Id */
            player_id: string;
            /** Player Name */
            player_name: string;
            /** Team */
            team: string;
            /** Week */
            week: number;
            /** Position */
            position: string | null;
            /** Jersey Number */
            jersey_number: number | null;
            /** Headshot Url */
            headshot_url: string | null;
            /** Attempts */
            attempts: number;
            /** Completions */
            completions: number;
            /** Pass Yards */
            pass_yards: number;
            /** Pass Tds */
            pass_tds: number;
            /** Interceptions Thrown */
            interceptions_thrown: number;
            /** Sacks Taken */
            sacks_taken: number;
            /** Pass Epa */
            pass_epa: number;
            /** Targets */
            targets: number;
            /** Receptions */
            receptions: number;
            /** Rec Yards */
            rec_yards: number;
            /** Rec Tds */
            rec_tds: number;
            /** Air Yards */
            air_yards: number;
            /** Yac */
            yac: number;
            /** Rec Epa */
            rec_epa: number;
            /** Carries */
            carries: number;
            /** Rush Yards */
            rush_yards: number;
            /** Rush Tds */
            rush_tds: number;
            /** Rush Epa */
            rush_epa: number;
            /** Solo Tackles */
            solo_tackles: number;
            /** Assist Tackles */
            assist_tackles: number;
            /** Tackles For Loss */
            tackles_for_loss: number;
            /** Sacks */
            sacks: number;
            /** Qb Hits */
            qb_hits: number;
            /** Def Interceptions */
            def_interceptions: number;
            /** Pass Breakups */
            pass_breakups: number;
            /** Forced Fumbles */
            forced_fumbles: number;
            /** Fumble Recoveries */
            fumble_recoveries: number;
            /** Fg Att */
            fg_att: number;
            /** Fg Made */
            fg_made: number;
            /** Xp Att */
            xp_att: number;
            /** Xp Made */
            xp_made: number;
            /** Punts */
            punts: number;
            /** Punt Yards */
            punt_yards: number;
            /** Punt Returns */
            punt_returns: number;
            /** Punt Return Yards */
            punt_return_yards: number;
            /** Punt Return Tds */
            punt_return_tds: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * InjuryStatus
         * @description A weekly injury report entry. We surface the most recent one for a
         *     player on the player view; a list for team/game views.
         */
        InjuryStatus: {
            /** Season */
            season: number;
            /** Week */
            week: number;
            /** Team */
            team: string;
            /** Report Primary Injury */
            report_primary_injury: string | null;
            /** Report Secondary Injury */
            report_secondary_injury: string | null;
            /** Report Status */
            report_status: string | null;
            /** Practice Primary Injury */
            practice_primary_injury: string | null;
            /** Practice Status */
            practice_status: string | null;
            /** Full Name */
            full_name: string | null;
            /** Position */
            position: string | null;
            /** Gsis Id */
            gsis_id: string | null;
        };
        /**
         * KickingStats
         * @description Per-season kicker/punter splits derived from play-by-play — sparse by role.
         *
         *     Raw counts/totals are stored (not pre-computed rates) so the frontend can
         *     aggregate a career row by simple summation and recompute averages against
         *     the season-total attempt/punt counts it already has.
         */
        KickingStats: {
            /** Fg Long */
            fg_long?: number | null;
            /** Fg 0 39 Made */
            fg_0_39_made?: number | null;
            /** Fg 0 39 Att */
            fg_0_39_att?: number | null;
            /** Fg 40 49 Made */
            fg_40_49_made?: number | null;
            /** Fg 40 49 Att */
            fg_40_49_att?: number | null;
            /** Fg 50 Made */
            fg_50_made?: number | null;
            /** Fg 50 Att */
            fg_50_att?: number | null;
            /** Fg Blocked */
            fg_blocked?: number | null;
            /** Punt Net Yards */
            punt_net_yards?: number | null;
            /** Punt Inside 20 */
            punt_inside_20?: number | null;
            /** Punt Touchbacks */
            punt_touchbacks?: number | null;
            /** Punt Long */
            punt_long?: number | null;
            /** Punt Blocked */
            punt_blocked?: number | null;
        };
        /**
         * LeagueLeader
         * @description One row per player in /leaders. Stat fields are season totals from
         *     SUM() over player_game_stats, returned as DOUBLE.
         *
         *     All stat fields are required-and-non-null: the underlying columns have
         *     DEFAULT 0, so SUM(...) is always a number (0.0 for non-applicable
         *     stats like RB pass_yards). Roster-joined fields (position/team) may be
         *     null because the join is LEFT and roster data can be missing.
         */
        LeagueLeader: {
            /** Player Id */
            player_id: string;
            /** Player Name */
            player_name: string;
            /** Position */
            position: string | null;
            /** Team */
            team: string | null;
            /** Headshot Url */
            headshot_url: string | null;
            /** Games Played */
            games_played: number;
            /** Attempts */
            attempts: number;
            /** Completions */
            completions: number;
            /** Pass Yards */
            pass_yards: number;
            /** Pass Tds */
            pass_tds: number;
            /** Interceptions Thrown */
            interceptions_thrown: number;
            /** Sacks Taken */
            sacks_taken: number;
            /** Pass Epa */
            pass_epa: number;
            /** Carries */
            carries: number;
            /** Rush Yards */
            rush_yards: number;
            /** Rush Tds */
            rush_tds: number;
            /** Rush Epa */
            rush_epa: number;
            /** Targets */
            targets: number;
            /** Receptions */
            receptions: number;
            /** Rec Yards */
            rec_yards: number;
            /** Rec Tds */
            rec_tds: number;
            /** Yac */
            yac: number;
            /** Air Yards */
            air_yards: number;
            /** Rec Epa */
            rec_epa: number;
            /** Solo Tackles */
            solo_tackles: number;
            /** Assist Tackles */
            assist_tackles: number;
            /** Tackles For Loss */
            tackles_for_loss: number;
            /** Sacks */
            sacks: number;
            /** Qb Hits */
            qb_hits: number;
            /** Def Interceptions */
            def_interceptions: number;
            /** Pass Breakups */
            pass_breakups: number;
            /** Forced Fumbles */
            forced_fumbles: number;
            /** Fumble Recoveries */
            fumble_recoveries: number;
            /** Fg Att */
            fg_att: number;
            /** Fg Made */
            fg_made: number;
            /** Xp Att */
            xp_att: number;
            /** Xp Made */
            xp_made: number;
            /** Punts */
            punts: number;
            /** Punt Yards */
            punt_yards: number;
        };
        /** LineupPlayer */
        LineupPlayer: {
            /** Player Id */
            player_id: string | null;
            /** Pfr Player Id */
            pfr_player_id: string | null;
            /** Player Name */
            player_name: string;
            /** Team */
            team: string;
            /** Position */
            position: string | null;
            /** Position Group */
            position_group: string | null;
            /** Jersey Number */
            jersey_number: number | null;
            /** Headshot Url */
            headshot_url: string | null;
            /** Rating */
            rating: number | null;
            /** Raw Score */
            raw_score: number | null;
            /** Snaps */
            snaps: number;
            /** Snap Pct */
            snap_pct: number | null;
            /**
             * Scored Td
             * @default false
             */
            scored_td: boolean;
        };
        /** LineupScoringEvent */
        LineupScoringEvent: {
            /** Team */
            team: string | null;
            /** Player Id */
            player_id: string | null;
            /** Player Name */
            player_name: string | null;
            /** Kind */
            kind: string;
            /** Qtr */
            qtr: number | null;
            /** Clock */
            clock: string | null;
            /** Distance */
            distance: number | null;
            /** Desc */
            desc: string | null;
        };
        /** LineupTeam */
        LineupTeam: {
            /** Team */
            team: string;
            /**
             * Side
             * @enum {string}
             */
            side: "away" | "home";
            /** Avg Rating */
            avg_rating: number | null;
            /** Offense Avg */
            offense_avg?: number | null;
            /** Defense Avg */
            defense_avg?: number | null;
            /** Ol Grade */
            ol_grade?: number | null;
            /** Offense Personnel */
            offense_personnel: string | null;
            /** Defense Personnel */
            defense_personnel: string | null;
            /** Offense */
            offense: components["schemas"]["LineupPlayer"][];
            /** Defense */
            defense: components["schemas"]["LineupPlayer"][];
            /** Rotation */
            rotation: components["schemas"]["LineupPlayer"][];
        };
        /**
         * LiveGameOut
         * @description A game as the live tier reports it.
         *
         *     Deliberately an overlay rather than a second copy of `Game`: it carries
         *     `game_id`, so the client merges it onto the cards it already has instead of
         *     learning a parallel vocabulary for the same fixture.
         */
        LiveGameOut: {
            /** Game Id */
            game_id: string | null;
            /** Away Team */
            away_team: string;
            /** Home Team */
            home_team: string;
            /** Gameday */
            gameday: string;
            /**
             * State
             * @enum {string}
             */
            state: "pre" | "in" | "post";
            /** Away Score */
            away_score: number | null;
            /** Home Score */
            home_score: number | null;
            /** Period */
            period: number | null;
            /** Clock */
            clock: string | null;
            /** Possession */
            possession: string | null;
            /** Detail */
            detail: string | null;
            /** Away Periods */
            away_periods: number[];
            /** Home Periods */
            home_periods: number[];
            /** Down Distance */
            down_distance: string | null;
            /** Red Zone */
            red_zone: boolean;
            /** Last Play */
            last_play: string | null;
            /** Away Timeouts */
            away_timeouts: number | null;
            /** Home Timeouts */
            home_timeouts: number | null;
            /** Leaders */
            leaders: components["schemas"]["LiveLeaderOut"][];
        };
        /**
         * LiveLeaderOut
         * @description A game leader. `detail` is the source's own phrasing, passed through.
         */
        LiveLeaderOut: {
            /**
             * Category
             * @enum {string}
             */
            category: "passing" | "rushing" | "receiving";
            /** Player */
            player: string;
            /** Team */
            team: string | null;
            /** Detail */
            detail: string;
        };
        /** LoadSeasonResponse */
        LoadSeasonResponse: {
            /** Season */
            season: number;
            /**
             * Status
             * @enum {string}
             */
            status: "loaded" | "scheduled" | "queued" | "loading" | "error" | "available";
        };
        /**
         * NgsStats
         * @description Next Gen Stats per season. Fields populated depend on role.
         *
         *     NOTE: unlike most of our models, these sub-views are genuinely sparse —
         *     a QB row only has passing fields, a WR row only has receiving fields.
         *     The helper builds the dict from non-null SELECT results, so absent
         *     fields mean "doesn't apply." Defaults are kept so each instance can
         *     carry any subset.
         */
        NgsStats: {
            /** Avg Time To Throw */
            avg_time_to_throw?: number | null;
            /** Adot */
            adot?: number | null;
            /** Avg Completed Air Yards */
            avg_completed_air_yards?: number | null;
            /** Cpoe */
            cpoe?: number | null;
            /** Aggressiveness */
            aggressiveness?: number | null;
            /** Expected Cmp Pct */
            expected_cmp_pct?: number | null;
            /** Ngs Passer Rating */
            ngs_passer_rating?: number | null;
            /** Rush Yoe */
            rush_yoe?: number | null;
            /** Rush Yoe Per Att */
            rush_yoe_per_att?: number | null;
            /** Rush Efficiency */
            rush_efficiency?: number | null;
            /** Avg Time To Los */
            avg_time_to_los?: number | null;
            /** Pct Vs 8 Defenders */
            pct_vs_8_defenders?: number | null;
            /** Avg Separation */
            avg_separation?: number | null;
            /** Avg Cushion */
            avg_cushion?: number | null;
            /** Avg Target Depth */
            avg_target_depth?: number | null;
            /** Avg Yac */
            avg_yac?: number | null;
            /** Avg Yac Above Exp */
            avg_yac_above_exp?: number | null;
            /** Catch Pct */
            catch_pct?: number | null;
            /** Air Yards Share */
            air_yards_share?: number | null;
        };
        /**
         * PlayerAdvStats
         * @description Per-season advanced stats — sparse by player role.
         */
        PlayerAdvStats: {
            /** Fumbles Lost */
            fumbles_lost?: number | null;
            /** Target Share */
            target_share?: number | null;
            /** Air Yards Share */
            air_yards_share?: number | null;
            /** Stuff Rate */
            stuff_rate?: number | null;
            /** Stuffed */
            stuffed?: number | null;
            /** Carries Total */
            carries_total?: number | null;
            /** Def Tds */
            def_tds?: number | null;
            /** Penalties */
            penalties?: number | null;
            /** Penalty Yards */
            penalty_yards?: number | null;
            /** False Starts */
            false_starts?: number | null;
            /** Holding */
            holding?: number | null;
        };
        /**
         * PlayerAward
         * @description A single major award win for a player.
         *
         *     Sourced from the seeded `player_awards` table — major postseason
         *     voting awards: MVP, OPOY, DPOY, OROY, DROY, CPOY. Joined back to
         *     rosters on (player_name, season) during ingest so each row carries
         *     the player's gsis_id when available.
         */
        PlayerAward: {
            /** Season */
            season: number;
            /** Award */
            award: string;
            /** Team */
            team: string | null;
            /** Position */
            position: string | null;
        };
        /** PlayerChart */
        PlayerChart: {
            /** Game Id */
            game_id: string;
            /** Player Id */
            player_id: string;
            /** Player Name */
            player_name: string | null;
            /** Team */
            team: string | null;
            /** Position */
            position: string | null;
            /** Role */
            role: string;
            /** Rating */
            rating: number | null;
            /** Snap Pct */
            snap_pct: number | null;
            /** Stats */
            stats: {
                [key: string]: number | string | null;
            };
            /** Events */
            events: components["schemas"]["PlayerChartEvent"][];
        };
        /** PlayerChartEvent */
        PlayerChartEvent: {
            /** Play Id */
            play_id: number | null;
            /** Qtr */
            qtr: number | null;
            /** Clock */
            clock: string | null;
            /** Role */
            role: string;
            /** Lane */
            lane: string | null;
            /** Air Yards */
            air_yards: number | null;
            /** Yards */
            yards: number | null;
            /** Epa */
            epa: number | null;
            /** Outcome */
            outcome: string;
            /** Desc */
            desc: string | null;
        };
        /**
         * PlayerComparable
         * @description Cosine-similarity neighbor returned by /players/{id}/comparables.
         */
        PlayerComparable: {
            /** Player Id */
            player_id: string;
            /** Player Name */
            player_name: string;
            /** Position */
            position: string | null;
            /** Team */
            team: string | null;
            /** Headshot Url */
            headshot_url: string | null;
            /** Similarity */
            similarity: number;
            /** Games */
            games: number;
            /** First Season */
            first_season: number;
            /** Last Season */
            last_season: number;
            /** Pass Yards */
            pass_yards: number;
            /** Pass Tds */
            pass_tds: number;
            /** Rush Yards */
            rush_yards: number;
            /** Rush Tds */
            rush_tds: number;
            /** Carries */
            carries: number;
            /** Rec Yards */
            rec_yards: number;
            /** Rec Tds */
            rec_tds: number;
            /** Targets */
            targets: number;
            /** Att */
            att: number;
            /** Cmp */
            cmp: number;
            /** Ints */
            ints: number;
        };
        /**
         * PlayerGame
         * @description One row in the player's game log.
         */
        PlayerGame: {
            /** Game Id */
            game_id: string;
            /** Season */
            season: number;
            /** Week */
            week: number;
            /** Team */
            team: string;
            /** Opponent */
            opponent: string;
            /**
             * Location
             * @enum {string}
             */
            location: "home" | "away";
            /** Gameday */
            gameday: string | null;
            /** Away Score */
            away_score: number | null;
            /** Home Score */
            home_score: number | null;
            /** Result */
            result: ("W" | "L" | "T") | null;
            /** Game Type */
            game_type: string;
            /** Position */
            position: string | null;
            /** Jersey Number */
            jersey_number: number | null;
            /** Headshot Url */
            headshot_url: string | null;
            /** Attempts */
            attempts: number;
            /** Completions */
            completions: number;
            /** Pass Yards */
            pass_yards: number;
            /** Pass Tds */
            pass_tds: number;
            /** Interceptions Thrown */
            interceptions_thrown: number;
            /** Sacks Taken */
            sacks_taken: number;
            /** Pass Epa */
            pass_epa: number;
            /** Targets */
            targets: number;
            /** Receptions */
            receptions: number;
            /** Rec Yards */
            rec_yards: number;
            /** Rec Tds */
            rec_tds: number;
            /** Air Yards */
            air_yards: number;
            /** Yac */
            yac: number;
            /** Rec Epa */
            rec_epa: number;
            /** Carries */
            carries: number;
            /** Rush Yards */
            rush_yards: number;
            /** Rush Tds */
            rush_tds: number;
            /** Rush Epa */
            rush_epa: number;
            /** Solo Tackles */
            solo_tackles: number;
            /** Assist Tackles */
            assist_tackles: number;
            /** Tackles For Loss */
            tackles_for_loss: number;
            /** Sacks */
            sacks: number;
            /** Qb Hits */
            qb_hits: number;
            /** Def Interceptions */
            def_interceptions: number;
            /** Pass Breakups */
            pass_breakups: number;
            /** Forced Fumbles */
            forced_fumbles: number;
            /** Fumble Recoveries */
            fumble_recoveries: number;
            /** Fg Att */
            fg_att: number;
            /** Fg Made */
            fg_made: number;
            /** Xp Att */
            xp_att: number;
            /** Xp Made */
            xp_made: number;
            /** Punts */
            punts: number;
            /** Punt Yards */
            punt_yards: number;
            /** Punt Returns */
            punt_returns: number;
            /** Punt Return Yards */
            punt_return_yards: number;
            /** Punt Return Tds */
            punt_return_tds: number;
        };
        /**
         * PlayerProfile
         * @description Full /players/{id} payload.
         */
        PlayerProfile: {
            /** Player Id */
            player_id: string;
            /** Player Name */
            player_name: string;
            /** Position */
            position: string | null;
            /** Team */
            team: string | null;
            /** Jersey Number */
            jersey_number: number | null;
            /** Headshot Url */
            headshot_url: string | null;
            /** Height */
            height: number | null;
            /** Weight */
            weight: number | null;
            /** Age */
            age: number | null;
            /** College */
            college: string | null;
            /** Years Exp */
            years_exp: number | null;
            /** Entry Year */
            entry_year: number | null;
            /** Rookie Year */
            rookie_year: number | null;
            /** Draft Club */
            draft_club: string | null;
            /** Draft Number */
            draft_number: number | null;
            /** Games Played */
            games_played: number;
            /** Season Totals */
            season_totals: {
                [key: string]: number;
            };
            /** Games */
            games: components["schemas"]["PlayerGame"][];
            /** Ngs */
            ngs: {
                [key: string]: components["schemas"]["NgsStats"];
            };
            /** Snap Totals */
            snap_totals: {
                [key: string]: components["schemas"]["SnapTotals"];
            };
            /** Situational */
            situational: {
                [key: string]: components["schemas"]["SituationalStats"];
            };
            /** Kicking */
            kicking: {
                [key: string]: components["schemas"]["KickingStats"];
            };
            /** Wpa */
            wpa: {
                [key: string]: components["schemas"]["PlayerWpa"];
            };
            /** Adv Stats */
            adv_stats: {
                [key: string]: components["schemas"]["PlayerAdvStats"];
            };
            draft: components["schemas"]["DraftInfo"] | null;
            combine: components["schemas"]["CombineData"] | null;
            current_injury: components["schemas"]["InjuryStatus"] | null;
            depth: components["schemas"]["DepthChartEntry"] | null;
            /** Awards */
            awards: components["schemas"]["PlayerAward"][];
        };
        /**
         * PlayerSplit
         * @description One row of a player's stat line conditioned on a single situational
         *     dimension. Long-format: (season, category, split_dim, split_value) +
         *     metrics. Served by /players/{id}/splits, grouped client-side by dim.
         */
        PlayerSplit: {
            /** Season */
            season: number;
            /** Category */
            category: string;
            /** Split Dim */
            split_dim: string;
            /** Split Value */
            split_value: string;
            /** Sort Order */
            sort_order: number | null;
            /** Att */
            att: number | null;
            /** Cmp */
            cmp: number | null;
            /** Yards */
            yards: number | null;
            /** Td */
            td: number | null;
            /** Interceptions */
            interceptions: number | null;
            /** Air Yards */
            air_yards: number | null;
            /** Yac */
            yac: number | null;
            /** First Downs */
            first_downs: number | null;
            /** Epa */
            epa: number | null;
            /** Success Pct */
            success_pct: number | null;
            /** Cpoe */
            cpoe: number | null;
        };
        /**
         * PlayerWpa
         * @description Per-season WPA attribution. Sparse by role (passer/rusher/receiver).
         */
        PlayerWpa: {
            /** Pass Wpa */
            pass_wpa?: number | null;
            /** Rec Wpa */
            rec_wpa?: number | null;
            /** Rush Wpa */
            rush_wpa?: number | null;
        };
        /** PowerRankingRow */
        PowerRankingRow: {
            /** Rank */
            rank: number;
            /** Team */
            team: string;
            /** Record */
            record: string;
            /** Net Epa Play */
            net_epa_play: number | null;
            /** Movement */
            movement: number | null;
        };
        /** QuarterScore */
        QuarterScore: {
            /** Qtr */
            qtr: number;
            /** Away */
            away: number;
            /** Home */
            home: number;
        };
        /**
         * RosterPlayer
         * @description A player on a team's roster for a given season.
         */
        RosterPlayer: {
            /** Player Id */
            player_id: string;
            /** Player Name */
            player_name: string;
            /** Position */
            position: string | null;
            /** Jersey Number */
            jersey_number: number | null;
            /** Headshot Url */
            headshot_url: string | null;
        };
        /**
         * ScheduleWeek
         * @description A week of games returned by /schedule.
         */
        ScheduleWeek: {
            /** Week */
            week: number;
            /** Games */
            games: components["schemas"]["Game"][];
        };
        /** Scoreboard */
        Scoreboard: {
            /** Games */
            games: components["schemas"]["LiveGameOut"][];
            /**
             * Source
             * @enum {string}
             */
            source: "live" | "stale" | "schedule";
            /** Poll After */
            poll_after: number | null;
            /** Fetched At */
            fetched_at: string;
        };
        /** ScoringPlay */
        ScoringPlay: {
            /** Qtr */
            qtr: number;
            /** Clock */
            clock: string | null;
            /** Team */
            team: string | null;
            /** Kind */
            kind: string;
            /** Desc */
            desc: string | null;
            /** Away Score */
            away_score: number;
            /** Home Score */
            home_score: number;
        };
        /**
         * SearchResult
         * @description A single search hit. `type` discriminates player vs team.
         */
        SearchResult: {
            /**
             * Type
             * @enum {string}
             */
            type: "player" | "team";
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Position */
            position: string | null;
            /** Team */
            team: string | null;
            /** Headshot Url */
            headshot_url: string | null;
        };
        /** SeasonStatus */
        SeasonStatus: {
            /** Season */
            season: number;
            /**
             * Status
             * @enum {string}
             */
            status: "loaded" | "scheduled" | "queued" | "loading" | "error" | "available";
        };
        /**
         * SituationalStats
         * @description Per-season situational splits — sparse by design. See NgsStats note.
         */
        SituationalStats: {
            /** Lng Pass */
            lng_pass?: number | null;
            /** Lng Rush */
            lng_rush?: number | null;
            /** Lng Rec */
            lng_rec?: number | null;
            /** Rz Pass Att */
            rz_pass_att?: number | null;
            /** Rz Cmp */
            rz_cmp?: number | null;
            /** Rz Pass Tds */
            rz_pass_tds?: number | null;
            /** Rz Targets */
            rz_targets?: number | null;
            /** Rz Rec Tds */
            rz_rec_tds?: number | null;
            /** Rz Carries */
            rz_carries?: number | null;
            /** Rz Rush Tds */
            rz_rush_tds?: number | null;
            /** Third Pass Att */
            third_pass_att?: number | null;
            /** Third Pass Fd */
            third_pass_fd?: number | null;
            /** Third Targets */
            third_targets?: number | null;
            /** Third Rec Fd */
            third_rec_fd?: number | null;
            /** Third Carries */
            third_carries?: number | null;
            /** Third Rush Fd */
            third_rush_fd?: number | null;
            /** Fd Pass */
            fd_pass?: number | null;
            /** Fd Rec */
            fd_rec?: number | null;
            /** Fd Rush */
            fd_rush?: number | null;
        };
        /**
         * SnapTotals
         * @description Per-season snap counts. snap_counts SQL always returns every column,
         *     just NULL where the player has no snaps of that type.
         */
        SnapTotals: {
            /** Season */
            season: number;
            /** Offense Snaps */
            offense_snaps: number | null;
            /** Defense Snaps */
            defense_snaps: number | null;
            /** St Snaps */
            st_snaps: number | null;
            /** Avg Offense Pct */
            avg_offense_pct: number | null;
            /** Avg Defense Pct */
            avg_defense_pct: number | null;
            /** Avg St Pct */
            avg_st_pct: number | null;
        };
        /** StandingsRow */
        StandingsRow: {
            /** Team */
            team: string;
            /** W */
            w: number;
            /** L */
            l: number;
            /** T */
            t: number;
            /** Pct */
            pct: number;
            /** Pf */
            pf: number;
            /** Pa */
            pa: number;
            /** Home */
            home: string;
            /** Away */
            away: string;
            /** Div */
            div: string;
            /** Strk */
            strk: string;
            /** Gb */
            gb: string;
        };
        /**
         * TeamAnalyticsResponse
         * @description /team-analytics?season=… returns the season plus per-team rows.
         */
        TeamAnalyticsResponse: {
            /** Season */
            season: number;
            /** League */
            league: components["schemas"]["TeamAnalyticsRow"][];
        };
        /**
         * TeamAnalyticsRow
         * @description One row per team. Rank columns are 1-based with 1 = best (for that team).
         *
         *     Higher-is-better metrics use DESC ranks; lower-is-better metrics use ASC,
         *     so rank=1 always means "best in the league" regardless of metric direction.
         *
         *     Most rate metrics can legitimately be NULL (e.g. PROE is NULL for seasons
         *     before nflfastR added pass_oe; rz_td_pct is NULL for teams that never
         *     reached the red zone), so all of them are required-but-nullable.
         */
        TeamAnalyticsRow: {
            /** Team */
            team: string;
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Ties */
            ties: number;
            /** Pf Total */
            pf_total: number;
            /** Pa Total */
            pa_total: number;
            /** Ppg */
            ppg: number | null;
            /** Papg */
            papg: number | null;
            /** Pt Diff Per Game */
            pt_diff_per_game: number | null;
            /** Pts Per Drive */
            pts_per_drive: number | null;
            /** Pts Per Drive Allowed */
            pts_per_drive_allowed: number | null;
            /** Total Drives */
            total_drives: number | null;
            /** Total Drives Allowed */
            total_drives_allowed: number | null;
            /** Rz Td Pct */
            rz_td_pct: number | null;
            /** Rz Td Pct Allowed */
            rz_td_pct_allowed: number | null;
            /** Off Turnovers Total */
            off_turnovers_total: number;
            /** Def Takeaways Total */
            def_takeaways_total: number;
            /** Turnover Diff Per Game */
            turnover_diff_per_game: number | null;
            /** Off Plays Count */
            off_plays_count: number | null;
            /** Off Epa Play */
            off_epa_play: number | null;
            /** Off Pass Epa */
            off_pass_epa: number | null;
            /** Off Rush Epa */
            off_rush_epa: number | null;
            /** Off Success Pct */
            off_success_pct: number | null;
            /** Off Explosive Pct */
            off_explosive_pct: number | null;
            /** Proe */
            proe: number | null;
            /** Third Down Pct */
            third_down_pct: number | null;
            /** Def Epa Play */
            def_epa_play: number | null;
            /** Def Pass Epa */
            def_pass_epa: number | null;
            /** Def Rush Epa */
            def_rush_epa: number | null;
            /** Def Success Pct */
            def_success_pct: number | null;
            /** Def Explosive Pct */
            def_explosive_pct: number | null;
            /** Def Sack Pct */
            def_sack_pct: number | null;
            /** Third Down Stop Pct */
            third_down_stop_pct: number | null;
            /** Ppg Rank */
            ppg_rank: number | null;
            /** Pts Per Drive Rank */
            pts_per_drive_rank: number | null;
            /** Off Epa Play Rank */
            off_epa_play_rank: number | null;
            /** Off Pass Epa Rank */
            off_pass_epa_rank: number | null;
            /** Off Rush Epa Rank */
            off_rush_epa_rank: number | null;
            /** Off Success Rank */
            off_success_rank: number | null;
            /** Off Explosive Rank */
            off_explosive_rank: number | null;
            /** Third Down Rank */
            third_down_rank: number | null;
            /** Rz Td Rank */
            rz_td_rank: number | null;
            /** Proe Rank */
            proe_rank: number | null;
            /** Papg Rank */
            papg_rank: number | null;
            /** Pts Per Drive Allowed Rank */
            pts_per_drive_allowed_rank: number | null;
            /** Def Epa Play Rank */
            def_epa_play_rank: number | null;
            /** Def Pass Epa Rank */
            def_pass_epa_rank: number | null;
            /** Def Rush Epa Rank */
            def_rush_epa_rank: number | null;
            /** Def Success Rank */
            def_success_rank: number | null;
            /** Def Explosive Rank */
            def_explosive_rank: number | null;
            /** Third Down Stop Rank */
            third_down_stop_rank: number | null;
            /** Rz Td Allowed Rank */
            rz_td_allowed_rank: number | null;
            /** Def Sack Rank */
            def_sack_rank: number | null;
            /** Pt Diff Rank */
            pt_diff_rank: number | null;
            /** To Diff Rank */
            to_diff_rank: number | null;
        };
        /**
         * TeamGame
         * @description A team's schedule row inside /teams/{team}. Records walked forward
         *     by attach_records() are required (always set on this endpoint).
         */
        TeamGame: {
            /** Game Id */
            game_id: string;
            /** Season */
            season: number;
            /** Week */
            week: number;
            /** Gameday */
            gameday: string | null;
            /** Gametime */
            gametime: string | null;
            /** Away Team */
            away_team: string;
            /** Home Team */
            home_team: string;
            /** Away Score */
            away_score: number | null;
            /** Home Score */
            home_score: number | null;
            /** Stadium */
            stadium: string | null;
            /** Roof */
            roof: string | null;
            /** Surface */
            surface: string | null;
            /** Temp */
            temp: number | null;
            /** Wind */
            wind: number | null;
            /** Away Record */
            away_record: string | null;
            /** Home Record */
            home_record: string | null;
        };
        /**
         * TeamGameStats
         * @description Team-level box-score line for one game, computed from play-by-play.
         */
        TeamGameStats: {
            /** Team */
            team: string;
            /** Plays */
            plays: number;
            /** First Downs */
            first_downs: number;
            /** Third Att */
            third_att: number;
            /** Third Conv */
            third_conv: number;
            /** Fourth Att */
            fourth_att: number;
            /** Fourth Conv */
            fourth_conv: number;
            /** Penalties */
            penalties: number;
            /** Penalty Yards */
            penalty_yards: number;
            /** Turnovers */
            turnovers: number;
            /** Epa Play */
            epa_play: number | null;
            /** Success Pct */
            success_pct: number | null;
        };
        /**
         * TeamLeader
         * @description Per-player season totals for one team. Returned twice on /teams/{team}:
         *     once for regular season (leaders), once for playoffs (playoff_leaders).
         */
        TeamLeader: {
            /** Player Id */
            player_id: string;
            /** Player Name */
            player_name: string;
            /** Position */
            position: string | null;
            /** Jersey Number */
            jersey_number: number | null;
            /** Headshot Url */
            headshot_url: string | null;
            /** Games Played */
            games_played: number;
            /** Attempts */
            attempts: number;
            /** Completions */
            completions: number;
            /** Pass Yards */
            pass_yards: number;
            /** Pass Tds */
            pass_tds: number;
            /** Interceptions Thrown */
            interceptions_thrown: number;
            /** Sacks Taken */
            sacks_taken: number;
            /** Pass Epa */
            pass_epa: number;
            /** Carries */
            carries: number;
            /** Rush Yards */
            rush_yards: number;
            /** Rush Tds */
            rush_tds: number;
            /** Rush Epa */
            rush_epa: number;
            /** Targets */
            targets: number;
            /** Receptions */
            receptions: number;
            /** Rec Yards */
            rec_yards: number;
            /** Rec Tds */
            rec_tds: number;
            /** Air Yards */
            air_yards: number;
            /** Yac */
            yac: number;
            /** Rec Epa */
            rec_epa: number;
            /** Solo Tackles */
            solo_tackles: number;
            /** Assist Tackles */
            assist_tackles: number;
            /** Tackles For Loss */
            tackles_for_loss: number;
            /** Sacks */
            sacks: number;
            /** Qb Hits */
            qb_hits: number;
            /** Def Interceptions */
            def_interceptions: number;
            /** Pass Breakups */
            pass_breakups: number;
            /** Forced Fumbles */
            forced_fumbles: number;
            /** Fumble Recoveries */
            fumble_recoveries: number;
        };
        /**
         * TeamProfile
         * @description Response for /teams/{team}?season=…
         */
        TeamProfile: {
            /** Team */
            team: string;
            /** Season */
            season: number;
            /** Games */
            games: components["schemas"]["TeamGame"][];
            /** Leaders */
            leaders: components["schemas"]["TeamLeader"][];
            /** Playoff Leaders */
            playoff_leaders: components["schemas"]["TeamLeader"][];
        };
        /**
         * TeamSplit
         * @description One row of a team's rate profile conditioned on a situational dimension.
         *     Long-format: (side, split_dim, split_value) + rate metrics. Served by
         *     /teams/{team}/splits, grouped client-side by side + dim.
         */
        TeamSplit: {
            /** Side */
            side: string;
            /** Split Dim */
            split_dim: string;
            /** Split Value */
            split_value: string;
            /** Sort Order */
            sort_order: number | null;
            /** Plays */
            plays: number | null;
            /** Epa Play */
            epa_play: number | null;
            /** Success Pct */
            success_pct: number | null;
            /** Pass Rate */
            pass_rate: number | null;
            /** Yards Play */
            yards_play: number | null;
            /** Explosive Pct */
            explosive_pct: number | null;
            /** Pass Epa */
            pass_epa: number | null;
            /** Rush Epa */
            rush_epa: number | null;
        };
        /** ToolCall */
        ToolCall: {
            /** Tool */
            tool: string;
            /** Args */
            args: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WinProbPlay */
        WinProbPlay: {
            /** Game Seconds Remaining */
            game_seconds_remaining: number;
            /** Qtr */
            qtr: number;
            /** Home Wp */
            home_wp: number;
            /** Touchdown */
            touchdown: number;
            /** Interception */
            interception: number;
            /** Fumble Lost */
            fumble_lost: number;
            /** Posteam */
            posteam: string | null;
            /** Desc */
            desc: string | null;
        };
        /**
         * WpaLeader
         * @description One row in passing/rushing/receiving WPA leaders.
         *
         *     The volume column (attempts/carries/receptions) varies per sub-list.
         *     Only one is populated per row — the others are simply absent from
         *     the SQL projection, so they remain optional + None.
         */
        WpaLeader: {
            /** Player Id */
            player_id: string;
            /** Player Name */
            player_name: string;
            /** Position */
            position: string | null;
            /** Team */
            team: string | null;
            /** Headshot Url */
            headshot_url: string | null;
            /** Wpa */
            wpa: number;
            /** Games Played */
            games_played: number;
            /** Attempts */
            attempts?: number | null;
            /** Carries */
            carries?: number | null;
            /** Receptions */
            receptions?: number | null;
        };
        /**
         * WpaLeaders
         * @description The full /wpa-leaders payload: three sub-lists.
         */
        WpaLeaders: {
            /** Passing */
            passing: components["schemas"]["WpaLeader"][];
            /** Rushing */
            rushing: components["schemas"]["WpaLeader"][];
            /** Receiving */
            receiving: components["schemas"]["WpaLeader"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_seasons_api_seasons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeasonStatus"][];
                };
            };
        };
    };
    load_season_api_seasons__year__load_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadSeasonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    season_progress_api_seasons__year__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schedule_api_schedule_get: {
        parameters: {
            query?: {
                season?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleWeek"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_games_api_games_get: {
        parameters: {
            query: {
                week: number;
                season?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_api_games__game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_ratings_api_games__game_id__ratings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GamePlayerRating"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_lineup_api_games__game_id__lineup_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameLineup"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_player_chart_api_games__game_id__players__player_id__chart_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerChart"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_api_players__player_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_comparables_api_players__player_id__comparables_get: {
        parameters: {
            query?: {
                n?: number;
            };
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerComparable"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_splits_api_players__player_id__splits_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerSplit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_def_splits_api_players__player_id__def_splits_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefensiveSplit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_api_teams__team__get: {
        parameters: {
            query?: {
                season?: number;
            };
            header?: never;
            path: {
                team: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_roster_api_teams__team__roster_get: {
        parameters: {
            query?: {
                season?: number;
            };
            header?: never;
            path: {
                team: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterPlayer"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_depth_chart_api_teams__team__depth_chart_get: {
        parameters: {
            query?: {
                season?: number;
                week?: number | null;
            };
            header?: never;
            path: {
                team: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepthChartEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_splits_api_teams__team__splits_get: {
        parameters: {
            query?: {
                season?: number;
            };
            header?: never;
            path: {
                team: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamSplit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_injuries_api_teams__team__injuries_get: {
        parameters: {
            query?: {
                season?: number;
                week?: number | null;
            };
            header?: never;
            path: {
                team: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InjuryStatus"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_analytics_api_team_analytics_get: {
        parameters: {
            query?: {
                season?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamAnalyticsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leaders_api_leaders_get: {
        parameters: {
            query?: {
                season?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueLeader"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wpa_leaders_api_wpa_leaders_get: {
        parameters: {
            query?: {
                season?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WpaLeaders"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_standings_api_standings_get: {
        parameters: {
            query?: {
                season?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DivisionStandings"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_power_rankings_api_power_rankings_get: {
        parameters: {
            query?: {
                season?: number;
                week?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PowerRankingRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_api_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_stream_api_ask_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gaps_api_gaps_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scoreboard_api_live_scoreboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scoreboard"];
                };
            };
        };
    };
}
